'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { calculateQuote as coreCalculateQuote, createBookingFor, emailFor, notify, type BookingInput } from '@/lib/booking-core';
const text=(v:FormDataEntryValue|null)=>String(v||'').trim();
const configured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
async function currentUser(){if(!configured())throw new Error('Supabase is not configured.');const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');return [supabase,user] as const}
// validate / priceQuote / fetchDistanceKm / createBookingFor مستضافة الآن في lib/booking-core.ts
export async function signIn(form:FormData){if(!configured())throw new Error('Supabase is not configured.');const s=await createClient();const {error}=await s.auth.signInWithPassword({email:text(form.get('email')),password:text(form.get('password'))});if(error)throw new Error(error.message)}
export async function signUp(form:FormData){if(!configured())throw new Error('Supabase is not configured.');const role=text(form.get('role'));if(role!=='customer'&&role!=='dealer')throw new Error('Select a valid account type.');const s=await createClient();const {error}=await s.auth.signUp({email:text(form.get('email')),password:text(form.get('password')),options:{data:{role,full_name:text(form.get('full_name')),phone:text(form.get('phone')),dealer_name:text(form.get('dealer_name')),city:text(form.get('city')),address:text(form.get('address'))}}});if(error)throw new Error(error.message)}
export async function calculateQuote(origin:string,destination:string,days:number,pricePerDay:number,extraPerKm:number){return coreCalculateQuote(origin,destination,days,pricePerDay,extraPerKm)}
// emailFor / notify مستضافان الآن في lib/booking-core.ts
export async function createBooking(data:BookingInput){const [s,user]=await currentUser();await createBookingFor(s,user,data);revalidatePath('/dashboard')}
export async function respondBooking(id:string,status:'confirmed'|'rejected'){const [s]=await currentUser();const {data:booking,error}=await s.rpc('respond_to_booking',{p_booking_id:id,p_status:status});if(error||!booking)throw new Error(error?.message||'Booking was already handled.');let message='Your booking request was rejected.';if(status==='confirmed'){const {data:dealer}=await s.from('dealers').select('address,phone').eq('id',booking.dealer_id).single();message=`Your booking is confirmed. Address: ${dealer?.address||''}; phone: ${dealer?.phone||''}.`;}await notify(await emailFor(booking.customer_id),`Mishwar booking ${status}`,message);revalidatePath('/dashboard');revalidatePath('/bookings')}
const requireBody=(body:string)=>{const message=String(body??'').trim();if(message.length<1||message.length>1000)throw new Error('الرسالة لازم تكون من حرف لـ 1000 حرف.');return message}
const escHtml=(v:string)=>v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
export async function sendBookingMessage(bookingId:string,body:string){const message=requireBody(body);const [s,user]=await currentUser();const {data:booking,error}=await s.from('bookings').select('id,customer_id,dealers!inner(id,user_id)').eq('id',bookingId).single();const dealer=booking?.dealers as {user_id:string}|undefined;if(error||!booking)throw new Error('الحجز ده مش موجود أو مش متاح للدردشة.');const customer=booking.customer_id===user.id;const owner=!customer&&dealer?.user_id===user.id;if(!customer&&!owner)throw new Error('مش من أطراف الحجز ده.');const sender_role=customer?'customer':'dealer';const {error:insertError}=await s.from('booking_messages').insert({booking_id:bookingId,sender_id:user.id,sender_role,body:message});if(insertError)throw new Error(insertError.message);const to=customer?await emailFor(dealer!.user_id):await emailFor(booking.customer_id);await notify(to,customer?'رسالة جديدة من العميل على حجزك في مشوار':'رسالة جديدة من المعرض على حجزك في مشوار',`<p>وصلتك رسالة جديدة في محادثة الحجز:</p><p>${escHtml(message)}</p>`)}
export async function sendDealerAdminMessage(dealerId:string,body:string){const message=requireBody(body);const [s,user]=await currentUser();const {data:profile}=await s.from('profiles').select('role').eq('id',user.id).maybeSingle();const isAdmin=profile?.role==='super_admin';const {data:dealer,error:dealerError}=await s.from('dealers').select('user_id').eq('id',dealerId).single();if(dealerError||!dealer)throw new Error('المعرض ده مش موجود.');if(!isAdmin&&dealer.user_id!==user.id)throw new Error('مش مسموح تكتب في المحادثة دي.');const sender_role=isAdmin?'super_admin':'dealer';const {error:insertError}=await s.from('dealer_admin_messages').insert({dealer_id:dealerId,sender_id:user.id,sender_role,body:message});if(insertError)throw new Error(insertError.message)}
