'use server';
import { createClient as createAdminClient } from '@supabase/supabase-js';
import { revalidatePath } from 'next/cache';
import { sendNotification } from '@/lib/notifications';
import { createClient } from '@/lib/supabase/server';
const text=(v:FormDataEntryValue|null)=>String(v||'').trim();
const configured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
async function currentUser(){if(!configured())throw new Error('Supabase is not configured.');const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');return [supabase,user] as const}
function validate(destination:string,days:number,date:string){if(destination.length<2||destination.length>100)throw new Error('Enter a valid destination city.');if(!Number.isInteger(days)||days<1||days>90)throw new Error('Trip duration must be 1–90 days.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Enter a valid start date.');}
export async function signIn(form:FormData){if(!configured())throw new Error('Supabase is not configured.');const s=await createClient();const {error}=await s.auth.signInWithPassword({email:text(form.get('email')),password:text(form.get('password'))});if(error)throw new Error(error.message)}
export async function signUp(form:FormData){if(!configured())throw new Error('Supabase is not configured.');const role=text(form.get('role'));if(role!=='customer'&&role!=='dealer')throw new Error('Select a valid account type.');const s=await createClient();const {error}=await s.auth.signUp({email:text(form.get('email')),password:text(form.get('password')),options:{data:{role,full_name:text(form.get('full_name')),phone:text(form.get('phone')),dealer_name:text(form.get('dealer_name')),city:text(form.get('city')),address:text(form.get('address'))}}});if(error)throw new Error(error.message)}
export async function calculateQuote(origin:string,destination:string,days:number,pricePerDay:number,extraPerKm:number){validate(destination.trim(),days,new Date().toISOString().slice(0,10));if(!process.env.GOOGLE_MAPS_API_KEY)throw new Error('Google Maps API is not configured.');const url=new URL('https://maps.googleapis.com/maps/api/distancematrix/json');url.searchParams.set('origins',`${origin}, Egypt`);url.searchParams.set('destinations',`${destination}, Egypt`);url.searchParams.set('key',process.env.GOOGLE_MAPS_API_KEY);const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('Distance service is unavailable.');const payload=await response.json();const element=payload.rows?.[0]?.elements?.[0];if(element?.status!=='OK'||typeof element.distance?.value!=='number')throw new Error('Unable to calculate this route.');const distanceKm=Math.round(element.distance.value/10)/100;return {distanceKm,totalPrice:Math.round((days*pricePerDay+distanceKm*extraPerKm)*100)/100}}
async function emailFor(userId:string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key||!process.env.NEXT_PUBLIC_SUPABASE_URL)return null;const admin=createAdminClient(process.env.NEXT_PUBLIC_SUPABASE_URL,key);const {data}=await admin.auth.admin.getUserById(userId);return data.user?.email??null}
async function notify(to:string|null,subject:string,html:string){if(!to)return;try{await sendNotification({to,subject,html})}catch(error){console.error('Notification failed:',error)}}
export async function createBooking(data:{carId:string;destination:string;days:number;startDate:string;terms:boolean}){if(!data.terms)throw new Error('You must accept the terms.');validate(data.destination.trim(),data.days,data.startDate);const [s,user]=await currentUser();const {data:car,error}=await s.from('cars').select('id,dealer_id,price_per_day,extra_per_km,dealers!inner(city,status,user_id)').eq('id',data.carId).eq('status','available').single();const dealer=car?.dealers as unknown as {city:string;status:string;user_id:string}|undefined;if(error||!car||!dealer||dealer.status!=='approved')throw new Error('This car is no longer available.');const quote=await calculateQuote(dealer.city,data.destination.trim(),data.days,Number(car.price_per_day),Number(car.extra_per_km));const {error:insertError}=await s.from('bookings').insert({customer_id:user.id,dealer_id:car.dealer_id,car_id:car.id,origin_city:dealer.city,destination_city:data.destination.trim(),distance_km:quote.distanceKm,start_date:data.startDate,days:data.days,price_per_day:car.price_per_day,extra_per_km:car.extra_per_km,total_price:quote.totalPrice,terms_accepted_at:new Date().toISOString()});if(insertError)throw new Error(insertError.message);await notify(await emailFor(dealer.user_id),'New Mishwar booking request',`A customer requested a car trip to ${data.destination.trim()}.`);revalidatePath('/dashboard')}
export async function respondBooking(id:string,status:'confirmed'|'rejected'){const [s]=await currentUser();const {data:booking,error}=await s.rpc('respond_to_booking',{p_booking_id:id,p_status:status});if(error||!booking)throw new Error(error?.message||'Booking was already handled.');let message='Your booking request was rejected.';if(status==='confirmed'){const {data:dealer}=await s.from('dealers').select('address,phone').eq('id',booking.dealer_id).single();message=`Your booking is confirmed. Address: ${dealer?.address||''}; phone: ${dealer?.phone||''}.`;}await notify(await emailFor(booking.customer_id),`Mishwar booking ${status}`,message);revalidatePath('/dashboard');revalidatePath('/bookings')}
